{
 "title": "Quarkus Fault Tolerance",
 "description": "Displays metrics collected by methods annotated with MicroProfile Fault Tolerance annotations",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "base_ft_invocations_total" } },
   { "name": "avg_period", "label": "Moving Average Period", "query": "30s, 1m, 3m, 5m, 10m" },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": "0.5, 0.75, 0.95, 0.98, 0.99, 0.999"
   },
   { "name": "topK", "label": "Top K Values", "query": "3,5,10" }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard displays metrics collected by methods that are annotated with [MicroProfile Fault Tolerance](https://github.com/eclipse/microprofile-fault-tolerance/) annotations.\n\nIf no methods are annotated with a given Fault Tolerance Strategy, e.g. `@Retry`, then the respective panels will display \"No data\". This differs from no methods __applying__ the strategy, which would display 0 (or similar)."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Basic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fallbacks [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with `@Fallback`) which resulted in fallback being applied over the past $avg_period.\n\nIf no methods are annotated with `@Fallback`, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(increase(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period]))*100/\nsum without (result, fallback)(increase(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Retries [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with `@Retry`) which resulted in a retry over the past $avg_period.\n\nIf no methods are annotated with `@Retry`, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (retryResult, retried)(increase(base_ft_retry_calls_total{instance=~`${instance}`, retried='true'}[$avg_period]))*100/\nsum without (retryResult, retried)(increase(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Timeouts [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with `@Timeout`) which resulted in a timeout over the past $avg_period.\n\nIf no methods are annotated with `@Timeout`, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (timedOut)(increase(base_ft_timeout_calls_total{instance=~`${instance}`, timedOut='true'}[$avg_period]))*100/\nsum without (timedOut)(increase(base_ft_timeout_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Bulkhead Rejections [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with `@Bulkhead`) which were rejected by the bulkhead over the last $avg_period.\n\nIf no methods are annotated with `@Bulkhead`, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (bulkheadResult)(increase(base_ft_bulkhead_calls_total{instance=~`${instance}`, bulkheadResult='rejected'}[$avg_period]))*100/\nsum without (bulkheadResult)(increase(base_ft_bulkhead_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Circuit Breaker Rejections [$avg_period]",
   "type": "stat",
   "description": "The percentage of method invocations (for methods annotated with `@CircuitBreaker`) which were rejected by an open circuit breaker over the last $avg_period.\n\nIf no methods are annotated with `@CircuitBreaker`, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (circuitBreakerResult)(increase(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='circuitBreakerOpen'}[$avg_period])*100)\n/\nsum without (circuitBreakerResult)(increase(base_ft_circuitbreaker_calls_total{instance=~`${instance}`}[$avg_period]))"
    }
   ]
  },
  {
   "title": "Top $topK most frequently failing methods over the last $avg_period",
   "type": "table",
   "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place, including fallback.\n\nIf no methods annotated with fault tolerance annotations are failing after the strategies have been applied, \"No data\" will be displayed.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(${topK}, \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period])) \n) \n> 0 "
    }
   ]
  },
  {
   "title": "Method invocations [per second, avg $avg_period]",
   "type": "timeseries",
   "description": "Number of method invocations which occurred per second for methods with fault tolerance annotations.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Failure rate [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of calls which resulted in a failure.\n\nThis graph is showing failures after all fault tolerance processing has taken place, including fallback.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Fallback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations triggering fallback [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of method invocations which resulted in fallback being applied over the past $avg_period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Invocations failed after fallback [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of method invocations which failed once fallback had been applied.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied',result='exceptionThrown'}[$avg_period])) * 100 \n/ \nsum without (result, fallback)(rate(base_ft_invocations_total{instance=~`${instance}`, fallback='applied'}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Retry Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations failed despite retries [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of method invocation which failed, despite retrying, over the last $avg_period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (retryResult, retried)(rate(base_ft_retry_calls_total{instance=~`${instance}`, retried='true', retryResult!='valueReturned'}[$avg_period])*100)\n/\nsum without (retryResult, retried)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Retries per invocation [avg $avg_period]",
   "type": "timeseries",
   "description": "Average number of retries which occurred for each method invocation.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without()(rate(base_ft_retry_retries_total{instance=~`${instance}`}[$avg_period]))\n/\nsum without (retried, retryResult)(rate(base_ft_retry_calls_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Timeout Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations timed out [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of invocations which timed out",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (timedOut)(rate(base_ft_timeout_calls_total{instance=~`${instance}`, timedOut='true'}[$avg_period])) * 100\n/\nsum without (timedOut)(rate(base_ft_timeout_calls_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Mean execution duration for methods with a timeout [s, avg 1000 exec.]",
   "type": "timeseries",
   "description": "The average duration a method with a timeout executes for to return a value, using a weighted average of the last 1000 executions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "base_ft_timeout_executionDuration_mean_seconds{instance=~`${instance}`}",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of execution duration for methods with a timeout [s, avg 1000 exec.]",
   "type": "timeseries",
   "description": "Shows the selected quantile of execution times using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms.)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "base_ft_timeout_executionDuration_seconds{instance=~`${instance}`, quantile=`${quantile}`}",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Bulkhead Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations rejected by bulkhead [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of calls which were rejected by a bulkhead over the last $avg_period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`, bulkheadResult='rejected'}[$avg_period])*100)\n/\nsum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Estimated number of attempted concurrent calls through a bulkhead [avg 1m]",
   "type": "timeseries",
   "description": "Estimate of the number of concurrent calls that are attempted through a bulkhead.\n\nThis is done by multiplying the number of attempted invocations by the mean execution time.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without (bulkheadResult)(rate(base_ft_bulkhead_calls_total{instance=~`${instance}`}[30s]))\n*\nbase_ft_bulkhead_runningDuration_mean_seconds{instance=~`${instance}`}",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Mean execution duration for methods with a bulkhead [s, avg 1000 exec.]",
   "type": "timeseries",
   "description": "The average duration a method with a bulkhead runs for to return a value, using a weighted average of the last 1000 executions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "base_ft_bulkhead_runningDuration_mean_seconds{instance=~`${instance}`}",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "$quantile quantile of execution duration for methods with a bulkhead [s, avg 1000 exec.]",
   "type": "timeseries",
   "description": "Shows the selected quantile of execution times, for methods running with a bulkhead, using a weighted average of the last 1000 executions.\n\nThe quantiles should be understood like this: if the 0.99 quantile is 300ms, then 99% of executions took less than 300ms. (Conversely, 1% of executions took longer than 300ms.)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "base_ft_bulkhead_runningDuration_seconds{instance=~`${instance}`, quantile=`${quantile}`}",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Invocations rejected by an open circuit breaker [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of calls which were rejected by an open circuit breaker over the last $avg_period.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='circuitBreakerOpen'}[$avg_period])*100)\n/\nsum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Failed calls permitted by circuit breaker [%, avg $avg_period]",
   "type": "timeseries",
   "description": "Percentage of invocations which were permitted to run by a circuit breaker but failed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "repeat": "method",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult='failure'}[$avg_period]))*100\n/\nsum without (circuitBreakerResult)(rate(base_ft_circuitbreaker_calls_total{instance=~`${instance}`, circuitBreakerResult=~'success|failure'}[$avg_period]))",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  },
  {
   "title": "Circuit breaker open or half-open [%]",
   "type": "timeseries",
   "description": "Shows the percentage of time per-second that a circuit breaker spends in an open or half-open state.\n\nThe graph checks back for up to 1 minute for the two most recent data points.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum without (state)(irate(base_ft_circuitbreaker_state_total_seconds{instance=~`${instance}`, state!='closed'}[1m])*100)",
     "legendFormat": "instance: {{instance}}, method: {{method}}"
    }
   ]
  }
 ]
}